CREATE DATABASE PROJECTS;

USE PROJECTS;

CREATE TABLE TASK(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FINALIZATION_DATE DATE DEFAULT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CLOSED BIT(1) NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE USER(
  USER VARCHAR(255) DEFAULT NULL,
  PASSWORD VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USER VALUES ('admin', 'admin');